### ISSUE TITLE
Discrepancy between the project.org file and spec

### ISSUE THREAD

**Issue by derekdowling** [abramhindle/CMPUT404-project-socialdistribution#14]
When comparing:
```
[ ] implement a restful API for http://service/post/postid
a PUT should insert/update a post
a POST should insert the post
a GET should get the post
```
and https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json#L13, there are no functional differences.

These endpoints are redundant and are most likely a result of @berjansk not realizing that a pre-existing call was defined in project.org for the same purpose, or a typo. My proposal would be to update the project.org specification of `http://services/post` to use `http://service/posts` as well since using the plural of post is the normal REST convention anyway and it'll bring it back in line with example-article.json.

**Comment by berjansk** [comment]
It makes sense to retrieve a post exclusively through http://service/post/postid

Could have been a typo on my part when I wrote up the changes in example-article.json .

**Comment by derekdowling** [comment]
Yeah, no biggie. It's just strange seeing everyone implement the a different route to do the same call everywhere. This should alleviate that.

**Comment by abramhindle** [comment]
For compatibility I suggest you treat those routes as aliases of each other.

**Comment by derekdowling** [comment]
I had this in mind for next year's spec.

**Comment by abramhindle** [comment]
Well I added a bit into project.org indicating you should make an alias for posts/id and post/id for compatibility.
